export const INCREASE_COUNTER="INCREASE_COUNTER"
export const DECREASE_COUNTER="DECREASE_COUNTER"
export const INCREASE_BY_TWO_COUNTER="INCREASE_BY_TWO_COUNTER"
export const INCREASE_BY_THREE_COUNTER="INCREASE_BY_Three_COUNTER"